/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OHRzyZHJbjk
 */
'use client'
import { AvatarImage, AvatarFallback, Avatar } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { useUser } from '@clerk/nextjs'
import Link from 'next/link'
import { buttonVariants } from '@/components/ui/button'
import { cn } from '@/lib/utils'

export function MyProfile() {
  const { user } = useUser()
  return (
    <>
      <Card className='mx-auto max-w-[350px] space-y-4 border-2 border-primary px-6 py-4'>
        <div className='flex items-center gap-3'>
          <Avatar className='h-12 w-12'>
            <AvatarImage alt='User avatar' src={user?.imageUrl} />
            <AvatarFallback>A</AvatarFallback>
          </Avatar>
          <div className='grid gap-0.5 text-lg'>
            <div className='font-semibold'>{user?.username}</div>
          </div>
        </div>
        <div className='flex justify-between'>
          <div className='flex items-center gap-2'>
            <GroupIcon className='h-6 w-6' />
            <span className='text-sm font-semibold'>Following</span>
            <Badge>1250</Badge>
          </div>
          <div className='flex items-center gap-2'>
            <PersonStandingIcon className='h-6 w-6' />
            <span className='text-sm font-semibold'>Followers</span>
            <Badge>980</Badge>
          </div>
        </div>
        <Link
          href='/profile'
          className={cn(buttonVariants({ variant: 'default' }), 'mt-2 w-full')}
        >
          Edit Profile
        </Link>
      </Card>
    </>
  )
}

function GroupIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M3 7V5c0-1.1.9-2 2-2h2' />
      <path d='M17 3h2c1.1 0 2 .9 2 2v2' />
      <path d='M21 17v2c0 1.1-.9 2-2 2h-2' />
      <path d='M7 21H5c-1.1 0-2-.9-2-2v-2' />
      <rect width='7' height='5' x='7' y='7' rx='1' />
      <rect width='7' height='5' x='10' y='12' rx='1' />
    </svg>
  )
}

function PersonStandingIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <circle cx='12' cy='5' r='1' />
      <path d='m9 20 3-6 3 6' />
      <path d='m6 8 6 2 6-2' />
      <path d='M12 10v4' />
    </svg>
  )
}
